### ISSUE TITLE
add citation?

### ISSUE THREAD

**Issue by guanhuaw** [albangossard/Bindings-NUFFT-pytorch#1]
Dear @albangossard 

Thanks for the excellent and helpful work! By any chance, if you are using the derivation of DOI: 10.1109/TCI.2023.3240081, could you please add the reference in the readme and comments? It would be helpful for the following researchers to debug and find the theory.

Best,
Guanhua

**Comment by albangossard** [comment]
Dear @guanhuaw
Thank you for your message, this is indeed a good idea. I've added a reference section in 50f1403.
Best,
Alban
